version: "3.9"
services:
  scraper:
    build: .
    stdin_open: true
    tty: true
    environment:
      - DB_PATH=/home/user/vol/scrape.db
      - PRODUCTS_YAML_FILE=/home/user/ww_products.yml
      - SECONDS_BETWEEN_SCRAPES=30
      - SNS_DISABLE_PUBLISH=${SNS_DISABLE_PUBLISH}
      - SNS_TOPIC_ARN=${SNS_TOPIC_ARN}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}

    volumes:
      - myapp:/home/user/vol
volumes:
  myapp: